info:
  contact: {}
paths:
  /api/user/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get user by id
      tags:
      - user
swagger: "2.0"
