basePath: /
definitions:
  domain.BaseResp:
    properties:
      data: {}
      message:
        type: string
      status:
        type: boolean
    type: object
  dto.AuthReq:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  dto.UserRegisterReq:
    properties:
      level:
        enum:
        - Superadmin
        - CS
        - Admin
        - Member
        - Silver
        - Gold
        example: Member
        type: string
      password:
        example: "123456"
        type: string
      username:
        example: johndoe
        type: string
      whatsapp:
        example: "+628123456789"
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Ini adalah dokumentasi API saya
  title: My Awesome API
  version: "1.0"
paths:
  /api/auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login Credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.AuthReq'
      produces:
      - application/json
      responses:
        "200":
          description: JWT Token
        "400":
          description: Invalid Request
        "401":
          description: Authentication Failed
      summary: Generate Token for Authentication
      tags:
      - auth
  /api/auth/refresh:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: New JWT Token
        "401":
          description: Authentication Failed
      security:
      - BearerAuth: []
      summary: Refresh JWT Token
      tags:
      - auth
  /api/auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: User Registration Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.UserRegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: Registration Success
          schema:
            $ref: '#/definitions/domain.BaseResp'
        "400":
          description: Invalid Request
          schema:
            $ref: '#/definitions/domain.BaseResp'
        "409":
          description: User already exists
          schema:
            $ref: '#/definitions/domain.BaseResp'
      summary: Register a new user
      tags:
      - auth
  /api/user/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: User Not Found
          schema:
            type: string
      summary: Get user by id
      tags:
      - user
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
